[[pages]]
path = "/"
screenshotTimestamp = "2026-06-19T11:32:48Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/6TrLUjj"

[[pages]]
path = "/price-list"
screenshotTimestamp = "2026-06-15T06:59:57Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/hZ4QY7j"

[[pages]]
path = "/purchases"
screenshotTimestamp = "2026-06-15T10:57:25Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/l3UrEWV"

[[pages]]
path = "/manufacturing"
screenshotTimestamp = "2026-06-18T12:27:00Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/DtdOhXr"

[[pages]]
path = "/billing"
screenshotTimestamp = "2026-06-19T08:04:47Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/1BsWhwW"

[[pages]]
path = "/invoices/50"
screenshotTimestamp = "2026-06-18T13:07:26Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/TVYzaQJ"

[[pages]]
path = "/settings"
screenshotTimestamp = "2026-06-18T13:30:22Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/KH2yqil"

[[pages]]
path = "/commission"
screenshotTimestamp = "2026-06-19T09:02:49Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/uKj2G9t"

[[pages]]
path = "/invoices"
screenshotTimestamp = "2026-06-19T08:17:17Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/CaELIDK"

[[pages]]
path = "/inventory"
screenshotTimestamp = "2026-06-19T10:01:08Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/t706Lpv"

[[pages]]
path = "/whatsapp-logs"
screenshotTimestamp = "2026-06-19T13:13:13Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ca30010b-ce55-4e52-92d9-1cd6b37a4c76/2905cf7a-0ac1-4fbc-af4d-72525d12d7bb/0uvUHrO"
